### ISSUE TITLE
Changing page size dynamically

### ISSUE THREAD

**Issue by yanis60** [fralx/LimeReport#166]
Hi,

Is it possible to change a page size dynamically using parameters?

It would be very useful

**Comment by fralx** [comment]
You can write in script something like this
```
Reportpage1.beforeRender.connect(before_page1_render);
function before_page1_render(){
	Reportpage1.setItemWidth(getVariable("PageWidth"));
	Reportpage1.setItemHeight(getVariable("PageHeight"));
}
```

**Comment by alonsomm2000** [comment]
Greetings, I tried your script with some changes, I pass on a variable called HalfPage=1 in order to create half page report:

Reportpage1.beforeRender.connect(before_page1_render);
function before_page1_render(){
if(getVariable("HalfPage")==1) Reportpage1.setItemHeight(139);
}

But paper seen to be reduced but page header does not show : (   Look:
![Limereport-page-resize-not-working](https://user-images.githubusercontent.com/15023328/58661184-7a72a980-82e4-11e9-91e8-fefb5bead274.png)

Any Idea how to fix this, I just need to change paper size on the fly to half page (8.5 x 5.5 inches)

Regards,
            Luis Murillo.

**Comment by alonsomm2000** [comment]
Finally I solve it my self, but here it is, just in case some want to do same thing.

To get it to work correctly reduce paper size to half page 8.5 x 5.5 inches, all you have to do is:

In your program add:
report->dataManager()->setReportVariable("HalfPage",1);

Then in your report, Script Tab, paste this:
Reportpage1.beforeRender.connect(before_page1_render);
function before_page1_render()
{
   if(getVariable("HalfPage")==1) Reportpage1.setHeight(139);
}

Regards, 
                Luis Murillo.
